# Generated by Django 4.0.2 on 2022-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/images')),
                ('Small', models.BooleanField(default=False)),
                ('Medium', models.BooleanField(default=False)),
                ('Large', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=120)),
            ],
        ),
    ]
